### ISSUE TITLE
IndexError: list index out of range - get_last_message 

### ISSUE THREAD

**Issue by BibiPush** [altryne/chatGPT-telegram-bot#17]
I got everything working except I don't receive the bot responses on the telegram app. However they show up in Chromium. 
```
(base) C:\GPT-3\chatGPT-telegram-bot-main>python server.py
2022-12-05 18:49:36,080 - apscheduler.scheduler - INFO - Scheduler started
2022-12-05 18:49:36,080 - telegram.ext._application - INFO - Application started
2022-12-05 18:49:45,705 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\telegram\ext\_application.py", line 1042, in process_update
    await coroutine
  File "C:\Users\admin\anaconda3\lib\site-packages\telegram\ext\_handler.py", line 143, in handle_update
    return await self.callback(update, context)
  File "C:\GPT-3\chatGPT-telegram-bot-main\server.py", line 111, in wrapper
    await func(update, context)
  File "C:\GPT-3\chatGPT-telegram-bot-main\server.py", line 173, in echo
    response = get_last_message()
  File "C:\GPT-3\chatGPT-telegram-bot-main\server.py", line 81, in get_last_message
    last_element = page_elements[-1]
IndexError: list index out of range
```

**Comment by mlee11705** [comment]
Same issue

**Comment by peterw** [comment]
pull the latest commit

**Comment by michaelgarydean** [comment]
> 

@peterw it's working for you with the commit from today, posting back in the telegram app?

**Comment by peterw** [comment]
yes @michaelgarydean

**Comment by mlee11705** [comment]
It works now! Thanks @peterw !

**Comment by trzy** [comment]
Looks like it might be broken again?

**Comment by BibiPush** [comment]
Works for me now as well ! ty @peterw

**Comment by photographyraptor** [comment]
modify server.py file in line 92 for:

page_elements = PAGE.query_selector_all(".prose")
