### ISSUE TITLE
loop stage on on playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by bugbounted** [altryne/chatGPT-telegram-bot#51]
Hi [altryne](https://github.com/altryne),
after deployed on railway.app using dockerfile embeded headless true env , going in loop error below many time repeat this :
```
Please log in to OpenAI Chat
Traceback (most recent call last):
Press enter when you're done
File "/app/server.py", line 307, in <module>
start_browser()
File "/app/server.py", line 272, in start_browser
PAGE.locator("button", has_text="Log in").click()
File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13670, in click
self._sync(
File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
return task.result()
File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
raise self._exception.with_traceback(self._exception_tb)
File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
result = coro.send(None)
File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 146, in click
return await self._frame.click(self._selector, strict=True, **params)
File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 489, in click
await self._channel.send("click", locals_to_params(locals()))
File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
return await self._connection.wrap_api_call(
File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
return await cb()
File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
result = next(iter(done)).result()
File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
raise self._exception.with_traceback(self._exception_tb)
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("button").filter(has_text="Log in")
============================================================
```
waiting for your commit/s for fix it.
finest regards

**Comment by khaivu-mta** [comment]
same issue here. i think it can't login with headless option.

**Comment by hsieh123** [comment]
Same here. perhaps a change of behavior at openai login page did this.

**Comment by tempalov** [comment]
can we wait for a fix?

**Comment by streamride** [comment]
This issue happens because of cloudflare protection. If you launch it on remote server. You can check by yourserlf if you launch with chromium ( not with firefox), so you need to handle cloudflare first to go further.

**Comment by nhan0905585682** [comment]
Let me ask if anyone has solved this problem yet? If so, give me the solution

**Comment by nhan0905585682** [comment]
I changed 
Browser = play.chromium.launch_persistent_context (    User_data_dir = "/Tmp/Playwright",    Headless = (os.getenv ('headless_browser', 'false') == 'True'))

**Comment by dragelecpc** [comment]
same issue, had anyone fixed it?

**Comment by jeck5001** [comment]
same issue, had anyone fixed it?
