### ISSUE TITLE
The bot does not send the chatgpt response message

### ISSUE THREAD

**Issue by ArteInverso** [altryne/chatGPT-telegram-bot#55]
The bot does not send the chatgpt response message

\chatGPT-telegram-bot-main\server.py", line 93, in get_last_message
    last_element = page_elements[-1]
IndexError: list index out of range

**Comment by romanki** [comment]
also face this issue: 

`2023-01-25 20:25:40,845 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/roman/miniconda3/envs/chat/lib/python3.10/site-packages/telegram/ext/_application.py", line 1042, in process_update
    await coroutine
  File "/Users/roman/miniconda3/envs/chat/lib/python3.10/site-packages/telegram/ext/_handler.py", line 143, in handle_update
    return await self.callback(update, context)
  File "/Users/roman/Documents/Project/bezdushnui_bot/chatGPT-telegram-bot/server.py", line 125, in wrapper
    if update.effective_user.id == user_id:
  File "/Users/roman/Documents/Project/bezdushnui_bot/chatGPT-telegram-bot/server.py", line 244, in echo
    await check_loading(update)
  File "/Users/roman/Documents/Project/bezdushnui_bot/chatGPT-telegram-bot/server.py", line 93, in get_last_message
    print(page_elements[-1].text)
IndexError: list index out of range`

**Comment by 1RB** [comment]
+ bump

**Comment by F33RNI** [comment]
same

**Comment by 1RB** [comment]
```js
// change this line
    page_elements = PAGE.query_selector_all("div[class*='request-']")

// to this
    page_elements = PAGE.query_selector_all("div[class*='lg:w-[calc(100%-115px)]']")
```
fixed in PR #45
