### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'click'

### ISSUE THREAD

**Issue by tckwgd** [altryne/chatGPT-telegram-bot#58]
I had problem as follows:
chatgpt-telegram-bot  | 2023-02-02 04:22:29,228 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
chatgpt-telegram-bot  | Traceback (most recent call last):
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1042, in process_update
chatgpt-telegram-bot  |     await coroutine
chatgpt-telegram-bot  |   File "/home/pwuser/.local/lib/python3.10/site-packages/telegram/ext/_handler.py", line 143, in handle_update
chatgpt-telegram-bot  |     return await self.callback(update, context)
chatgpt-telegram-bot  |   File "/app/server.py", line 125, in wrapper
chatgpt-telegram-bot  |     await func(update, context)
chatgpt-telegram-bot  |   File "/app/server.py", line 242, in echo
chatgpt-telegram-bot  |     send_message(update.message.text)
chatgpt-telegram-bot  |   File "/app/server.py", line 81, in send_message
chatgpt-telegram-bot  |     box.click()
chatgpt-telegram-bot  | AttributeError: 'NoneType' object has no attribute 'click'

**Comment by congluanbui** [comment]
Can change the email, password to API chatbot GPT? I test in another docker with API and it's working perfectly
