### ISSUE TITLE
Cant login when open chromium

### ISSUE THREAD

**Issue by congluanbui** [altryne/chatGPT-telegram-bot#59]
I cant login the account when chromium popup and the chromium does not have internet 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/17411550/216967809-441da2ee-230d-4abc-9987-5e27851ecf35.png">

**Comment by fyu0h** [comment]
git clone the latset version,don't download from release

**Comment by Lanme** [comment]
I can login but it soon come out another issue : ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1108)

**Comment by dragelecpc** [comment]
Can i run the docker image in VPS? I try and got this erro
chatgpt-telegram-bot     | Please log in to OpenAI Chat
chatgpt-telegram-bot     | Press enter when you're done
chatgpt-telegram-bot     | Traceback (most recent call last):
chatgpt-telegram-bot     |   File "/app/server.py", line 307, in <module>
chatgpt-telegram-bot     |     start_browser()
chatgpt-telegram-bot     |   File "/app/server.py", line 272, in start_browser
chatgpt-telegram-bot     |     PAGE.locator("button", has_text="Log in").click()
chatgpt-telegram-bot     |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13670, in click
chatgpt-telegram-bot     |     self._sync(
chatgpt-telegram-bot     |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
chatgpt-telegram-bot     |     return task.result()
chatgpt-telegram-bot     |   File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
chatgpt-telegram-bot     |     raise self._exception.with_traceback(self._exception_tb)
chatgpt-telegram-bot     |   File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
chatgpt-telegram-bot     |     result = coro.send(None)
chatgpt-telegram-bot     |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 146, in click
chatgpt-telegram-bot     |     return await self._frame.click(self._selector, strict=True, **params)
chatgpt-telegram-bot     |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 489, in click
chatgpt-telegram-bot     |     await self._channel.send("click", locals_to_params(locals()))
chatgpt-telegram-bot     |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
chatgpt-telegram-bot     |     return await self._connection.wrap_api_call(
chatgpt-telegram-bot     |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
chatgpt-telegram-bot     |     return await cb()
chatgpt-telegram-bot     |   File "/home/pwuser/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
chatgpt-telegram-bot     |     result = next(iter(done)).result()
chatgpt-telegram-bot     |   File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
chatgpt-telegram-bot     |     raise self._exception.with_traceback(self._exception_tb)
chatgpt-telegram-bot     | playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
chatgpt-telegram-bot     | =========================== logs ===========================
chatgpt-telegram-bot     | waiting for locator("button").filter(has_text="Log in")
chatgpt-telegram-bot     | ============================================================
chatgpt-telegram-bot exited with code 1
